name: HayerQuest
version: ${project.version}
api-version: 1.16
main: me.xiaozhangup.hayerquest.HayerQuest

depend:
  - IridiumSkyblock
  - Vault

commands:
  istodo:
    description: The island todo book
  ispull:
    description: Inside command
  isquestreload:
    description: Reload command